# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a15a2cc40f627456672fb4864ceefd3e8b288479b4f3bfedb43c2b01e3089977f0104f712b4cd9c360a3497c7bf278ebdbc14f9d2fdeecf06f4c6e6278a5223

test:
  secret_key_base: dcaf16b5b2c9b45345154f79e157ddbcd45693d0f47acfb1937ec95297adc0885e739a5c4b356498c7fc5cbef334c62bf1f6bb08c4a2dde502a33437ac9cb1bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
